// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

order _$orderFromJson(Map<String, dynamic> json) {
  return order(
    json['order_id'] as String,
    json['app_id'] as String,
    json['member_id'] as int,
    json['partner_id'] as int,
    json['store_id'] as int,
    json['order_from'] as int,
    json['order_type'] as int,
    json['fx_ref'] as String,
    json['mjs_activity_id'] as int,
    json['mby_activity_id'] as int,
    json['act_json'] as String,
    (json['total_fee'] as num)?.toDouble(),
    (json['discount_fee'] as num)?.toDouble(),
    json['discount_src'] as String,
    (json['mjs_discount_fee'] as num)?.toDouble(),
    json['balance_discount'] as int,
    json['adjust_fee'] as int,
    (json['post_fee'] as num)?.toDouble(),
    json['packing_fee'] as int,
    (json['payment'] as num)?.toDouble(),
    (json['total_tax'] as num)?.toDouble(),
    json['refund_amount'] as int,
    json['is_paid'] as int,
    json['shipping_corp'] as String,
    json['shipping_code'] as String,
    json['deliver_name'] as String,
    json['deliver_phone'] as String,
    json['email'] as String,
    json['country'] as String,
    json['province'] as String,
    json['city'] as String,
    json['district'] as String,
    json['deliver_address'] as String,
    json['post_code'] as String,
    json['status'] as String,
    json['lock_state'] as int,
    json['evaluation_state'] as int,
    json['refund_state'] as int,
    json['pay_way_id'] as int,
    json['pay_way_code'] as int,
    json['pickpoint_id'] as int,
    json['user_id'] as int,
    json['note'] as String,
    json['remark'] as String,
    (json['items'] as List)
        ?.map(
            (e) => e == null ? null : Items.fromJson(e as Map<String, dynamic>))
        ?.toList(),
    json['flow_type'] as int,
    (json['weight'] as num)?.toDouble(),
    json['food_id'] as String,
    (json['coupon_fee'] as num)?.toDouble(),
    json['account_json'] as String,
    (json['true_taxes_fee'] as num)?.toDouble(),
    json['profit_status'] as int,
    json['flag'] as int,
    json['use_integral'] as int,
    (json['integral_discount'] as num)?.toDouble(),
    json['active_code'] as String,
    json['custom_del'] as int,
    (json['pick_point_list'] as List)?.map((e) => e as int)?.toList(),
    json['err_msg'] as String,
    json['idName'] as String,
    json['idCard'] as String,
  );
}

Map<String, dynamic> _$orderToJson(order instance) => <String, dynamic>{
      'order_id': instance.orderId,
      'app_id': instance.appId,
      'member_id': instance.memberId,
      'partner_id': instance.partnerId,
      'store_id': instance.storeId,
      'order_from': instance.orderFrom,
      'order_type': instance.orderType,
      'fx_ref': instance.fxRef,
      'mjs_activity_id': instance.mjsActivityId,
      'mby_activity_id': instance.mbyActivityId,
      'act_json': instance.actJson,
      'total_fee': instance.totalFee,
      'discount_fee': instance.discountFee,
      'discount_src': instance.discountSrc,
      'mjs_discount_fee': instance.mjsDiscountFee,
      'balance_discount': instance.balanceDiscount,
      'adjust_fee': instance.adjustFee,
      'post_fee': instance.postFee,
      'packing_fee': instance.packingFee,
      'payment': instance.payment,
      'total_tax': instance.totalTax,
      'refund_amount': instance.refundAmount,
      'is_paid': instance.isPaid,
      'shipping_corp': instance.shippingCorp,
      'shipping_code': instance.shippingCode,
      'deliver_name': instance.deliverName,
      'deliver_phone': instance.deliverPhone,
      'email': instance.email,
      'country': instance.country,
      'province': instance.province,
      'city': instance.city,
      'district': instance.district,
      'deliver_address': instance.deliverAddress,
      'post_code': instance.postCode,
      'status': instance.status,
      'lock_state': instance.lockState,
      'evaluation_state': instance.evaluationState,
      'refund_state': instance.refundState,
      'pay_way_id': instance.payWayId,
      'pay_way_code': instance.payWayCode,
      'pickpoint_id': instance.pickpointId,
      'user_id': instance.userId,
      'note': instance.note,
      'remark': instance.remark,
      'items': instance.items,
      'flow_type': instance.flowType,
      'weight': instance.weight,
      'food_id': instance.foodId,
      'coupon_fee': instance.couponFee,
      'account_json': instance.accountJson,
      'true_taxes_fee': instance.trueTaxesFee,
      'profit_status': instance.profitStatus,
      'flag': instance.flag,
      'use_integral': instance.useIntegral,
      'integral_discount': instance.integralDiscount,
      'active_code': instance.activeCode,
      'custom_del': instance.customDel,
      'pick_point_list': instance.pickPointList,
      'err_msg': instance.errMsg,
      'idName': instance.idName,
      'idCard': instance.idCard,
    };

Items _$ItemsFromJson(Map<String, dynamic> json) {
  return Items(
    json['order_item_id'] as int,
    json['order_id'] as String,
    json['item_id'] as String,
    json['sku_id'] as String,
    json['outer_id'] as String,
    json['sku_outer_id'] as String,
    json['title'] as String,
    json['sku_properties'] as String,
    json['image'] as String,
    json['quantity'] as int,
    json['sku_stocks'] as int,
    (json['price'] as num)?.toDouble(),
    (json['total_fee'] as num)?.toDouble(),
    (json['discount_fee'] as num)?.toDouble(),
    json['discount_src'] as String,
    (json['packing_fee'] as num)?.toDouble(),
    (json['payment'] as num)?.toDouble(),
    (json['item_tax'] as num)?.toDouble(),
    json['limit_pay'] as String,
    json['activity_id'] as int,
    json['bargain_act_id'] as int,
    json['pintuan_id'] as int,
    json['pintuan_activity_id'] as int,
    json['start_date'] as String,
    json['end_date'] as String,
    json['act_json'] as String,
    json['updated_at'] as String,
    json['delivery_addrs'] as String,
    (json['weight'] as num)?.toDouble(),
    json['barcode'] as String,
    json['xtype'] as int,
    json['is_virtual'] as bool,
    (json['true_taxes_fee'] as num)?.toDouble(),
    json['refund_state'] as int,
    json['refund_amount'] as int,
  );
}

Map<String, dynamic> _$ItemsToJson(Items instance) => <String, dynamic>{
      'order_item_id': instance.orderItemId,
      'order_id': instance.orderId,
      'item_id': instance.itemId,
      'sku_id': instance.skuId,
      'outer_id': instance.outerId,
      'sku_outer_id': instance.skuOuterId,
      'title': instance.title,
      'sku_properties': instance.skuProperties,
      'image': instance.image,
      'quantity': instance.quantity,
      'sku_stocks': instance.skuStocks,
      'price': instance.price,
      'total_fee': instance.totalFee,
      'discount_fee': instance.discountFee,
      'discount_src': instance.discountSrc,
      'packing_fee': instance.packingFee,
      'payment': instance.payment,
      'item_tax': instance.itemTax,
      'limit_pay': instance.limitPay,
      'activity_id': instance.activityId,
      'bargain_act_id': instance.bargainActId,
      'pintuan_id': instance.pintuanId,
      'pintuan_activity_id': instance.pintuanActivityId,
      'start_date': instance.startDate,
      'end_date': instance.endDate,
      'act_json': instance.actJson,
      'updated_at': instance.updatedAt,
      'delivery_addrs': instance.deliveryAddrs,
      'weight': instance.weight,
      'barcode': instance.barcode,
      'xtype': instance.xtype,
      'is_virtual': instance.isVirtual,
      'true_taxes_fee': instance.trueTaxesFee,
      'refund_state': instance.refundState,
      'refund_amount': instance.refundAmount,
    };
